#!/usr/bin/bash

# gsettings
gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor'
gsettings set org.gnome.desktop.interface font-name 'Noto Sans 9'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
gsettings set org.gnome.desktop.interface cursor-theme 'Fluent-dark'


#hyprctl setcursor Sweet-cursors 24
