#!/bin/sh
swayidle -w \
	timeout 300 'brightnessctl set 50%' \
		resume 'brightnessctl set 100%' \
	timeout 1998 'lockscreen'\
			resume 'hyprctl dispatch dpms on' \
	timeout 2000 'hyprctl dispatch dpms off' \
		resume  'hyprctl dispatch dpms on' \
	timeout 15 'if pgrep gtklock; then hyprctl dispatch dpms off;fi' \
		resume 'hyprctl dispatch dpms on' \
	before-sleep 'lockscreen' \
		after-resume 'hyprctl dispatch dpms on' \
	lock 'lockscreen' \
