#!/bin/sh
swayidle -w \
	timeout 300 'brightnessctl set 50%' \
		resume 'brightnessctl set 100%' \
	timeout 895 'lockscreen'\
	timeout 900 'hyprctl dispatch dpms off' \
		resume  'hyprctl dispatch dpms on' \
	timeout 10 'if pgrep gtklock; then hyprctl dispatch dpms off;fi' \
		resume 'hyprctl dispatch dpms on' \
	before-sleep 'lockscreen' \
	lock 'lockscreen' \
