#!/usr/bin/env bash

# Autostart Programs ----------------------------------------#

# Polkit agent
[[ ! $(pgrep -f polkit-gnome-authentication-agent) ]] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Restore Wallpaper
wpgtk --restore &

# Screenlocker
killall -q -9 xss-lock
xss-lock --ignore-xss -l lockscreen &

# D-Bus
dbus-update-activation-environment --all

# xfce4-settings daemon
xfsettingsd &

# Enable Super Keys For Menu
killall -q -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager --daemon &

# Dunst (Notifications Daemon)
dunst &

# Compositor 
compositor --start &

# Touchpad Gestures
if libinput list-devices | grep -qiw 'Touchpad'; then
	killall -q -9 fusuma
	fusuma -d &
fi

# Launch Polybar
"$HOME"/.config/polybar/launch.sh &

## Launch System Tray
"$HOME"/.config/polybar/scripts/systray &

# CopyQ (Clipboard Daemon)
copyq --start-server &

# Plank (Dock)
plank &

# Conky
conky.sh &
