#!/bin/bash

if [[ -f "$HOME/.zprofile" ]]; then source "$HOME/.zprofile" ; else conky="On" ;fi

## Autostart Programs
#xdg-autostart &

## xfce4-settings daemon
xfsettingsd &

# Enable power management
xfce4-power-manager --daemon &

## Dunst (Notifications Daemon)
dunst &

## Picom (Compositor)	
picom -b &

## Restore Wallpaper
wal -Re &
sh "$HOME"/.local/bin/wpgtk run &

# Enable Super Keys For Menu
killall -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Launch Polybar
sh "$HOME"/.config/polybar/launch.sh &

# Launch System Tray
sh "$HOME"/.config/polybar/scripts/systray &

## CopyQ (Clipboard Daemon)
copyq --start-server &

## Plank (Dock)
plank &

## Conky
if [ $conky == "On" ]; then 
	sh "$HOME"/.local/bin/conky.sh &
fi
