#!/bin/bash

## Autostart Programs
	
## xfce4-settings daemon
xfsettingsd &

## Dunst (Notifications Daemon)
dunst &

## Picom (Compositor)	
picom --experimental-backends &

## Restore Wallpaper
wal -Re &
sh ~/.scripts/wpgtk run &

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

## Launch Polybar
sh ~/.config/polybar/launch.sh &

## CopyQ (Clipboard Daemon)
copyq --start-server &

## Stalonetray (System Tray)
~/.config/polybar/scripts/systray &

## Thunar Daemon
exec thunar --daemon &

## Plank (Dock)
exec plank &

## Excute Screenshot script
#exec sh ~/.scripts/check.sh &

## Discord Launch
#exec discord &

## Trackma Launch
#exec trackma-gtk &

## KDE Conenct
exec kdeconnect-indicator &
