#!/usr/bin/env bash

# A simple script to switch to the next or previous workspaces.
current="$(wmctrl -d | awk '/\*/{print $1}')"

# Function to switch to the next workspace.
next(){
	if [[ "$current" -lt 7 ]]; then
		wmctrl -s $(( $current + 1)) || echo "Error: Failed to switch to next workspace."
	else 
		wmctrl -s 0 || echo "Error: Failed to switch to workspace 1."
	fi
}

# Function to switch to the previous workspace.
prev(){
	if [[ "$current" -eq 0 ]]; then
		wmctrl -s 7 || echo "Error: Failed to switch to previous workspace."
	else
		wmctrl -s $(( $current - 1)) || echo "Error: Failed to switch to previous workspace."
	fi
}

# Function to display usage information.
usage(){
	echo "Usage: $0 [next|prev]"
}

# Check the number of arguments and call the appropriate function.
case "$1" in
	next)
		next
		;;
	prev)
		prev
		;;
	*)
		usage
		;;
esac
