#!/usr/bin/env bash

# Autostart Programs ----------------------------------------#

[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile" || conky="On"

# XDG Autostart 
[[ ! $(pgrep xfce-polkit) ]] && xdg-autostart &

# Keybinds
killall -q -9 sxhkd
sxhkd -c ~/.config/sxhkd/i3-sxhkdrc &

# Enable Super Keys For Menu
killall -q -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Polkit agent
#if [[ ! $(pidof xfce-polkit) ]]; then /usr/lib/xfce-polkit/xfce-polkit & ;fi 

# Fix cursor
xsetroot -cursor_name left_ptr &

# xfce4-settings daemon
xfsettingsd &

# Picom 
picom -b &

# Autotiling for i3
autotiling &

# Dunst
dunst &

# Restore Wallpaper
wal -Re &
"$HOME"/.local/bin/wpgtk run &

# Fix the i3 colors
"$HOME"/.config/i3/i3-reload

# Launch Polybar
"$HOME"/.config/polybar/launch.sh &

# Thunar 
thunar --daemon &

# CopyQ
copyq --start-server &

# Thunar 
[[ $(pgrep thunar) ]] && killall -9 thunar
thunar --daemon &

# Conky
[[ "$conky" == "On" ]] && "$HOME"/.local/bin/conky.sh &
