#!/usr/bin/env bash

# A simple script to switch to the next or previous workspace in i3.

# Initialize the $num variable with the current workspace number.
num=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).num')

# Function to switch to the next workspace.
next(){
	if [[ "$num" -lt 8 ]]; then
		i3-msg workspace number $(( $num + 1)) || echo "Error: Failed to switch to next workspace."
	else 
		i3-msg workspace number 1 || echo "Error: Failed to switch to workspace 1."
	fi
}

# Function to switch to the previous workspace.
prev(){
	if [[ "$num" -gt 1 ]]; then
		i3-msg workspace number $(( $num - 1)) || echo "Error: Failed to switch to previous workspace."
	else 
		i3-msg workspace number 8 || echo "Error: Failed to switch to workspace 8."
	fi
}

# Function to display usage information.
usage(){
	echo "Usage: $0 [next|prev]"
}

# Check the number of arguments and call the appropriate function.
case "$1" in
	next)
		next
		;;
	prev)
		prev
		;;
	*)
		usage
		;;
esac
