#!/usr/bin/env bash

state="$(i3-msg -t get_tree | jq | grep '"scratchpad_state": "fresh",' | wc -l)"

if [[ "$state" > 0 ]]; then 
	i3-msg scratchpad show && i3-msg floating toggle
else 
	i3-msg move scratchpad 
fi
	
