#!/bin/bash

case $1 in
    power)
       ~/.config/rofi/bin/powermenu
        ;;
    lock)
		lockscreen
        ;;
    blue)
        blueman-manager
        ;;
	wifi)
		~/.config/rofi/bin/network_menu
        ;;
	picker)
		color-gpick
        ;;
	settings)
		xfce4-settings-manager
        ;;
	power-settings)
		xfce4-settings-manager
        ;;
	display)
		xfce4-display-settings
        ;;
	volume)
		pavucontrol
        ;;
esac &
sh ~/.config/eww/scripts/controls.sh
