#!/bin/bash

close(){
	eww close-all
	polybar-msg action "#control.hook.1"
	rm ~/.cache/eww/control-center.eww
}

case $1 in
    power)
       ~/.config/rofi/bin/powermenu
        ;;
    blue)
        blueman-manager
        ;;
	wifi)
		~/.config/rofi/bin/network_menu
        ;;
	picker)
		color-gpick
        ;;
	settings)
		xfce4-settings-manager
        ;;
	power-settings)
		xfce4-settings-manager
        ;;
	display)
		xfce4-display-settings
        ;;
	volume)
		pavucontrol
        ;;
esac &
close

