#!/bin/sh

# This script displays battery icon according to the charge level and charging state

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `acpi`

bat=$(acpi -b)
state=$(echo ${bat} | awk '{print $3}')
rem="$(acpi | cut -d ' ' -f5 |cut -d ':' -f1-2)"
if [[ "$state" = "Not" ]]; then
    level=$(echo ${bat} | awk '{print $5}')
    level=${level::-1}
    
else
    level=$(echo ${bat} | awk '{print $4}')
    if [[ "$state" == *"Unknown"* ]]; then
        level=${level::-1}
    else
        if [[ "$level" == "100%" ]]; then
            level=${level::-1}
        else
            level=${level::-2}
        fi
    fi
fi

icon() {
    if [[ "$bat" == *"until"* ]]; then
        
        if [[ "$level" -ge "95" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "90" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "80" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "60" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "40" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "30" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "20" ]]; then
            echo "" "${level}%" "($rem)"
        else
            echo "" "${level}%" "($rem)"
        fi
    else
        if [[ "$level" -ge "95" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "90" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "80" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "70" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "60" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "50" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "40" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "30" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "20" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "10" ]]; then
            echo "" "${level}%" "($rem)"
        else
            echo "" "${level}%" "($rem)"
        fi
    fi
}

if [[ $1 = "-l" ]]; then
    echo "${level}%"
elif [[ $1 = "-i" ]]; then
	if [[ -z "$(acpi -V | grep -i Battery)" ]]; then 
		echo "" "AC"
	else
		icon 
	fi
fi
