#!/bin/sh

# This script displays battery icon according to the charge level and charging state

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `acpi`

bat=$(acpi -b)
state=$(echo ${bat} | awk '{print $3}')
rem="$(acpi | cut -d ' ' -f5 |cut -d ':' -f1-2)"
if [[ "$state" = "Not" ]]; then
    level=$(echo ${bat} | awk '{print $5}')
    level=${level::-1}
    
else
    level=$(echo ${bat} | awk '{print $4}')
    if [[ "$state" == *"Unknown"* ]]; then
        level=${level::-1}
    else
        if [[ "$level" == "100%" ]]; then
            level=${level::-1}
        else
            level=${level::-2}
        fi
    fi
fi

level() {
    if [[ "$bat" == *"until"* ]]; then
        
        if [[ "$level" -ge "95" ]]; then
            echo "" "${level}%" 
            elif [[ "$level" -ge "90" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "80" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "60" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "40" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "30" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "20" ]]; then
            echo "" "${level}%" "($rem)"
        else
            echo "" "${level}%" "($rem)"
        fi
    else
        if [[ "$level" == "100" ]]; then
            echo "" "${level}%"
            elif [[ "$level" -ge "95" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "90" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "80" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "70" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "60" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "50" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "40" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "30" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "20" ]]; then
            echo "" "${level}%" "($rem)"
            elif [[ "$level" -ge "10" ]]; then
            echo "" "${level}%" "($rem)"
        else
            echo "" "${level}%" "($rem)"
        fi
    fi
}

lock=/tmp/battery-saver.lock
comp(){
	cc=`grep "background" ~/.config/polybar/colors.ini | cut -d ' ' -f3`
	
	if [[ `pgrep picom` ]]; then 
		pkill picom 
		brightnessctl set 50%
		sed -i "s/opacity: .*/opacity: 1.0/g" ~/.config/alacritty/alacritty.yml
		sed -i -e "s/background = .*/background = ${cc::-2}/g" ~/.config/polybar/colors.ini
		sed -i -e "s/background: .*/background: ${cc::-2};/g" ~/.config/rofi/themes/colors.rasi		
		~/.config/polybar/launch.sh
	else
		picom -b
		brightnessctl set 100%
		sed -i "s/opacity: .*/opacity: 0.7/g" ~/.config/alacritty/alacritty.yml
		sed -i -e "s/background = .*/background = ${cc}00/g" ~/.config/polybar/colors.ini
		sed -i -e "s/background: .*/background: ${cc}90;/g" ~/.config/rofi/themes/colors.rasi
		~/.config/polybar/launch.sh
	fi
}

toggle(){
	if [[ -e $lock ]]; then 
		rm $lock &&
		comp
	else
		touch $lock &&
		comp
	fi
	
	}
status(){
	if [[ -e $lock ]]; then 
		echo "On"
	else
		echo "Off"
	fi
	}


if [[ $1 = "rem" ]]; then
    echo "($rem)"
elif [[ $1 = "status" ]]; then
	status
elif [[ $1 = "toggle" ]]; then
	toggle
elif [[ $1 = "level" ]]; then
	if [[ -z "$(acpi -V | grep -i Battery)" ]]; then 
		echo "" "AC"
	else
		level 
	fi
fi
