#!/bin/sh

# This script displays battery icon according to the charge level and charging state
# Dependencies: `acpi`

rem="$(acpi | cut -d ' ' -f5 |cut -d ':' -f1-2)"

level() {
	echo $( [ $(cat /sys/class/power_supply/BAT*/status) = "Charging" ] && echo "󰂄" || echo "󰂃 󰁺 󰁻 󰁻 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹" | cut -d' ' -f$(( $(cat /sys/class/power_supply/BAT*/capacity) / 10 + 1 )) ) "$(cat /sys/class/power_supply/BAT*/capacity)% ($(acpi | awk '{print $5}' | cut -d ":" -f1-2))"
}

lock=/tmp/battery-saver.lock
toggle(){
	cc=$(cat ~/.cache/wal/colors | head -n1)
	if [[ -e "$lock" ]]; then 
		rm $lock &&
		picom -b
		brightnessctl set +20%
		eww reload
	else
		touch $lock &&
		pkill picom 
		brightnessctl set 25%-
	fi
}
	
status(){
	if [[ -e $lock ]]; then 
		echo "On"
	else
		echo "Off"
	fi
	}


if [[ $1 = "rem" ]]; then
    echo "($rem)"
elif [[ $1 = "status" ]]; then
	status
elif [[ $1 = "toggle" ]]; then
	toggle
elif [[ $1 = "level" ]]; then
	if [[ -z "$(acpi -V | grep -i Battery)" ]]; then 
		echo "󰚥" "AC"
	else
		level 
	fi
fi
