#!/usr/bin/env bash

##--Bluetooth----------#
bt_state () {
  state=$(bluetoothctl show | grep 'Powered' | awk '{print $2}')
  if [[ $state == "yes" ]]; then
    echo on
  else
    echo off
  fi
}

bt_toggle () {
  state=$(bt_state)
  if [[ $state == "on" ]]; then
	bluetoothctl power off 2>&1 > /dev/null
  else
    bluetoothctl power on 2>&1 > /dev/null
  fi
}






if [[ $1 == "state" ]]; then
  bt_state
fi

if [[ $1 == "toggle" ]]; then
  bt_toggle
fi
