#!/usr/bin/env bash

STATUS=$(dunstctl is-paused)

toggle() {
    if [ $STATUS == "false" ]; then
        dunstctl set-paused true
    else
        dunstctl set-paused false
        icon="~/.local/share/icons/Papirus/24x24/panel/dino-status-dnd.svg"
		dunstify -u low --replace=97 "Do Not Disturb" -i $icon "Notifications are Unpaused" -u Normal
    fi
}

icon() {
    if [ $STATUS == "false" ]; then
        echo "󱑙"
    else
        echo "󰍶"
    fi
}

status() {
    if [ $STATUS == "false" ]; then
        echo "Off"
    else
        echo "On"
    fi
}

if [[ $1 == "toggle" ]]; then
    toggle
elif [[ $1 == "icon" ]]; then
    icon
elif [[ $1 == "status" ]]; then
    status
fi
