#!/bin/bash

config="$HOME/.config/eww"

while true ; do 
	if [[ ! -z "$(playerctl -l | head -n 1)" ]] &> /dev/null; then
		eww -c $config update music-panel=true
	else 
		eww -c $config update music-panel=false
	fi
	sleep 0.5
done 

