#!/bin/bash

players="spotify,%any,firefox,chromium,brave,mpd"
player_status=$(playerctl -p $players status)
artist=$(playerctl -p $players metadata --format '{{ artist }}')
title=$(playerctl -p $players metadata --format '{{ title }}')
albumart="$(playerctl -p $players metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
cache="$HOME/.cache/eww/music"

[ ! -d $cache ] && mkdir $cache

status_icon(){
    if [ "$player_status" = "Playing" ]; then
	    echo ""
    elif [ "$player_status" = "Paused" ]; then
	    echo ""
    else
	    echo ""
    fi
}

status_shuffle(){
	echo "$(playerctl -p ${players} shuffle)"
}
status_loop(){
	echo "$(playerctl -p ${players} loop)"
}

status_value () {
	player_name=$(playerctl -p $players -l | head -n 1 | cut -d '.' -f1)

	[ "$player_status" = "Playing" ] && echo "Now Playing - via ${player_name^}" || echo "Music"
}

title () {
    [ -z "$title" ] && echo "Nothing Playing" || echo $title
}

artist () {
    if [ "$title" = "Advertisement" ]; then
		echo "Spotify Free"
	else
		if [ -z "$artist" ]; then
			echo "Unknown Artist";
		else
			echo "by $artist"
		fi
	fi
}

cover () {
    cover="$cache/cover.png"
    fallback="$HOME/.config/wpg/templates/wallpaper.jpg"

    [ $(playerctl -p $players metadata mpris:artUrl) ] && curl -s "$albumart" --output $cover || cp $fallback $cover 
    echo $cover
}

position () {
    position=$(playerctl -p $players position)
	duration=$(playerctl -p $players metadata mpris:length | sed 's/.\{6\}$//')
	echo "scale=10; $position * 100/$duration" | bc

	#percent="$(( $position * 100 / $duration ))"
	#if [[ -z `playerctl metadata --format "{{ duration(mpris:length)}}"` ]]; then
		#echo "" 
	#else
		#playerctl metadata --format "{{duration(position) }} "/" {{ duration(mpris:length)}}"
    #fi
}

case $1 in
    status)
        status_value
    ;;
    status-icon)
        status_icon
    ;;
    title)
        title
    ;;
    artist)
        artist
    ;;
    title-artist)
        echo $(title) - $(artist)
    ;;
    cover)
        cover
    ;;
    cover-notification)
       cover_notification $2
    ;;
    position)
        position || echo "--:-- / --:-- "
    ;;
    shuffle)
        status_shuffle
    ;;
    loop)
        status_loop
    ;;
esac
