#!/usr/bin/env bash


# Variables and functions
MENUS_LIBDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! . "$MENUS_LIBDIR/pipemenu.cfg" 2> /dev/null; then
	echo "Error: Failed to locate pipemenu.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

if [[ -f "$HOME/.zprofile" ]]; then source "$HOME"/.zprofile ;else bar_style="base" ;fi

base(){
	sed -i 's/^bar_style=.*/bar_style=base/' "$HOME"/.zprofile
	"$HOME"/.config/polybar/launch.sh
	pkill stalonetray && "$HOME"/.config/polybar/scripts/systray &
}

minimal(){
	sed -i 's/^bar_style=.*/bar_style=minimal/' "$HOME"/.zprofile
	"$HOME"/.config/polybar/launch.sh
	pkill stalonetray && "$HOME"/.config/polybar/scripts/systray &
	pkill conky

}

if  [[ "$1" = "-b" ]]; then
	base
elif  [[ "$1" = "-m" ]]; then
	minimal
else
	if [[ "$bar_style" == "base" ]]; then 
		menuStart
			menuItem 'Switch to Minimal' "$0 -m"
			menuItem 'Reload' "$HOME/.config/polybar/launch.sh"
			menuItem 'Edit Config' "exo-open $HOME/.config/polybar/config.ini"
			menuItem 'Edit Modules' "exo-open $HOME/.config/polybar/modules.ini"
			menuItem 'Edit Weather Data' "exo-open $HOME/.config/polybar/scripts/info"
		menuEnd
	elif [[ "$bar_style" == "minimal" ]]; then 
		menuStart
			menuItem 'Switch to Base' "$0 -b"
			menuItem 'Reload Polybar' "$HOME/.config/polybar/launch.sh"
			menuItem 'Edit Config' "exo-open $HOME/.config/polybar/minimal/config-minimal.ini"
			menuItem 'Edit Modules' "exo-open $HOME/.config/polybar/minimal/modules-minimal.ini"
			menuItem 'Edit Weather Data' "exo-open $HOME/.config/polybar/scripts/info"
		menuEnd
	fi
fi


	
