#!/usr/bin/env bash

# Variables and functions
POLYCONF="$HOME/.config/polybar"
MENUS_LIBDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! . "$MENUS_LIBDIR/pipemenu.cfg" 2> /dev/null; then
	echo "Error: Failed to locate pipemenu.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile"
[[ -z "$bar_style" ]] && bar_style="base"

toggle_transparency(){
	picom_conf="$HOME/.config/picom/picom.conf"
	alacritty_conf="$HOME/.config/alacritty/alacritty.yml"
	wpgtk_dir="$HOME/.local/bin/wpgtk"
	pipe_dir="$HOME/.config/jgmenu/pipemenus/"
	
	if [[ "$1" == "bionic" ]]; then 
		"$pipe_dir"/compositor --disable-opacity
		"$pipe_dir"/compositor --enable-shadows
		"$pipe_dir"/wm-pipe --border 0
		sed -i "s/opacity: .*/opacity: 1.0/" "$alacritty_conf"
		sed -i "s/alpha=.*/alpha='FF'/" "$wpgtk_dir"
	elif [[ "$1" != "bionic" ]]; then
		"$pipe_dir"/compositor --enable-opacity
		"$pipe_dir"/compositor --disable-shadows
		"$pipe_dir"/wm-pipe --border "$window_border"
		sed -i "s/opacity: .*/opacity: 0.7/" "$alacritty_conf"
		sed -i "s/alpha=.*/alpha='60'/" "$wpgtk_dir"
	fi	
}

reload(){
	wpgtk partial
	[[ $(pgrep stalonetray) ]]
		pkill stalonetray && "$POLYCONF"/scripts/systray &> /dev/null
	polytray="$(pgrep -a polybar  | grep systray | cut -d ' ' -f1)"
	[[ "$polytray" ]] && "$POLYCONF"/scripts/systray
	exit
}

base(){
	sed -i 's/^bar_style=.*/bar_style=base/' "$HOME"/.zprofile
	toggle_transparency
	reload
}

minimal(){
	sed -i 's/^bar_style=.*/bar_style=minimal/' "$HOME"/.zprofile
	toggle_transparency
	reload
}

bionic(){
	sed -i 's/^bar_style=.*/bar_style=bionic/' "$HOME"/.zprofile
	toggle_transparency bionic
	reload
}

if  [[ "$1" ]]; then
	"$@"
else
	menuStart
		menuSeparator "Polybar (${bar_style^})"
		menuSubmenu '' 'Change Style'
			menuItem 'Base' "$0 base"
			menuItem 'Minimal' "$0 minimal"
			menuItem 'Bionic' "$0 bionic"
		menuSubmenuEnd
		menuItem 'Reload' "$0 reload"
		menuItem 'Edit Config' "exo-open $POLYCONF/$bar_style/config.ini"
		menuItem 'Edit Modules' "exo-open $POLYCONF/$bar_style/modules.ini"
		menuItem 'Edit Weather Data' "exo-open $POLYCONF/scripts/info"
	menuEnd
fi	
