#!/usr/bin/env bash

# Variables and functions
MENUS_LIBDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! . "$MENUS_LIBDIR/pipemenu.cfg" 2> /dev/null; then
	echo "Error: Failed to locate pipemenu.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

if command -v "envycontrol" >/dev/null 2>&1; then
	if [[ "$(envycontrol -q)" == "integrated" ]]; then
		menuStart
			menuSeparator 'envycontrol'
			menuItem 'Integrated (enabled)' "pkexec envycontrol -s integrated && notify-send -a envycontrol -r 72 'envycontrol' 'Reboot is required'"
			menuItem 'Hybrid' "pkexec envycontrol -s hybrid && notify-send -a envycontrol -r 72 'envycontrol' 'Reboot is required'"
		menuEnd
	elif [[ "$(envycontrol -q)" == "integrated" ]]; then
		menuStart
			menuSeparator 'envycontrol'
			menuItem 'Integrated ' "pkexec envycontrol -s integrated && notify-send -a envycontrol -r 72 'envycontrol' 'Reboot is required'"
			menuItem 'Hybrid (enabled)' "pkexec envycontrol -s hybrid && notify-send -a envycontrol -r 72 'envycontrol' 'Reboot is required'"
		menuEnd
	fi
	else
	menuItem 'Graphics not set up' ""
fi
