#!/usr/bin/env bash

# Pipemenu for Screen Recording with ffmpeg

state=$(recorder --status)

if [[ "$state" == "paused" ]]; then 
    menu+=("Resume Recording,recorder --toggle")
elif [[ "$state" == "on" ]]; then 
	menu+=("Pause Recording,recorder --toggle")
fi

if [[ "$state" == "paused" || "$state" == "on" ]]; then
    menu+=("Stop Recording,recorder --stop")
	menu+=("Discard Recording,recorder --cancel")
else
    menu+=("Record Desktop,recorder --screen")
    menu+=("Record Desktop (No Audio),recorder --screen-na")
    menu+=("Record Area,recorder --area")
    menu+=("Record Area (No Audio),recorder --area-na")
    menu+=("Record Audio Only,recorder --audio")
fi

printf '%s\n' "${menu[@]}"
