#!/usr/bin/env bash

## Pipemenu to take screenshots

menu+=("Screenshot Now,shot --now")
menu+=("Screenshot Area,shot --area")
menu+=("Screenshot Window,shot --win")
menu+=("Screenshot In 5s,shot --in5")
menu+=("^sep()")
menu+=("Upload to Imgur,shot --imgur")
menu+=("QR Scanner,shot --qr")
menu+=("Extract Text,shot --extract")

printf '%s\n' "${menu[@]}"
