#!/usr/bin/env bash

## Openbox Pipemenu to take screenshots with takeshot script

# Variables and functions
MENUS_LIBDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! . "$MENUS_LIBDIR/pipemenu.cfg" 2> /dev/null; then
	echo "Error: Failed to locate pipemenu.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

if [[ "$1" == "--now" ]]; then
	takeshot --now
elif [[ "$1" == "--in5" ]]; then
	takeshot --in5
elif [[ "$1" == "--in10" ]]; then
	takeshot --in10
elif [[ "$1" == "--win" ]]; then
	takeshot --win
elif [[ "$1" == "--area" ]]; then
	takeshot --area
else
    menuStart
        menuItem 'Screenshot Now' "$0 --now"
        menuItem 'Screenshot In 5s' "$0 --in5"
        menuItem 'Screenshot In 10s' "$0 --in10"
        menuItem 'Screenshot Area' "$0 --area"
        menuItem 'Screenshot Window' "$0 --win"
    menuEnd
fi

exit 0
