#!/usr/bin/env bash

## Pipemenu to take screenshots with takeshot script

if [[ "$1" == "--now" ]]; then
	takeshot --now
elif [[ "$1" == "--in5" ]]; then
	takeshot --in5
elif [[ "$1" == "--in10" ]]; then
	takeshot --in10
elif [[ "$1" == "--win" ]]; then
	takeshot --win
elif [[ "$1" == "--area" ]]; then
	takeshot --area
else
	menu+=("Screenshot Now,$0 --now")
	menu+=("Screenshot In 5s,$0 --in5")
	menu+=("Screenshot In 10s,$0 --in10")
	menu+=("Screenshot Area,$0 --area")
	menu+=("Screenshot Window,$0 --win")
	
	printf '%s\n' "${menu[@]}"
fi

exit 0
