#!/usr/bin/env bash

# Variables and functions
dots="$HOME/.dotfiles"

if [[ "$1" == "--clone" ]]; then
	if [ ! -d "$HOME/.dotfiles" ]; then 
		mkdir "$dots"
		terminal --float -e bash -c 'git clone --depth 1 https://github.com/totti786/dotfiles.git ~/.dotfiles'
	fi
	
	cd "$dots"
	if [[ "$(git rev-parse --is-inside-work-tree)" != "true" ]]; then 
		rm -R "$dots" && notify-send -r 34 'Cloning Failed' 
		exit 1
	fi
elif [[ "$1" == "--sys" ]]; then
	terminal --float -e bash -c 'sudo pacman -Syu && notify-send -a pacman "Updated Successfully" && cat > ~/.cache/pacman-updates'
elif [[ "$1" == "--dots" ]]; then
	cd "$dots"
	terminal --float -e sh "$dots"/install.sh --update &&
	## remove already existing json file for background color scheme
	rm "$HOME/.config/wpg/schemes/_home_$(whoami)__dotfiles_deps_background_jpg_dark_wal__1.1.0.json"
	## change wallpaper and update color scheme
	"$dots"/bin/.local/bin/wpgtk wall "$dots"/deps/background.jpg
elif [[ "$1" == "--wall" ]]; then
	cd "$dots"
	terminal --float -e sh "$dots"/install.sh --wallpapers
elif [[ ! -d "$HOME/.dotfiles" ]]; then 
	printf '%s\n' "Clone Repo,$0 --clone"
else
	menu+=("Update System,$0 --sys")
	menu+=("Update Configs,$0 --dots")
	menu+=("Update Wallpapers,$0 --wall")
	
	printf '%s\n' "${menu[@]}"
fi

exit 0
