#!/usr/bin/env bash

wm="$(wmctrl -m | head -n1 | cut -d " " -f2)"

# Varia# Variables and functions
MENUS_LIBDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

if ! . "$MENUS_LIBDIR/pipemenu.cfg" 2> /dev/null; then
	echo "Error: Failed to locate pipemenu.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

borderWidth(){
	if [[ "$1" ]]; then
		width="$1"
	else
	    if command -v "zenity" >/dev/null 2>&1; then
			width="$(zenity --scale --max-value 5 --text "Select Border Width:")"
		else
			notify-send "Error: zenity is not installed!"
		fi
	fi
	if [[ "$?" == 0 ]]; then
		if [[ "$wm" == "i3" ]]; then
			sed -i -e "s/pixel .*/pixel $width/g" "$HOME"/.config/i3/config &&
			"$HOME"/.config/i3/i3-reload
		elif [[ "$wm" == "bspwm" ]]; then
			sed -i -e "s/window_border=.*/window_border=\"$width\"/g" "$HOME"/.zprofile
			"$HOME"/.config/bspwm/bsp-border
		fi
	fi
	}

if  [[ "$1" = "--border" ]]; then
	borderWidth "$2"
else
	if [[ "$wm" == "bspwm" ]]; then
		menuStart
			menuSeparator 'bspwm'
			menuItem 'Edit Autostart' "exo-open $HOME/.config/bspwm/autostart"
			menuItem 'Edit config' "exo-open $HOME/.config/bspwm/bspwmrc"
			menuItem 'Edit keybinds' "exo-open $HOME/.config/sxhkd/sxhkdrc"
			menuItem 'Edit Border Width' "$0 --border"
			menuItem 'Restart bspwm' "bspc wm -r "
			menuItem 'Restart sxhkd' "pkill -USR1 -x sxhkd"
		menuEnd
	elif [[ "$wm" == "i3" ]]; then
		menuStart
			menuSeparator 'i3'
			menuItem 'Edit Autostart' "exo-open $HOME/.config/i3/autostart"
			menuItem 'Edit config' "exo-open $HOME/.config/i3/config"
			menuItem 'Edit keybinds' "exo-open $HOME/.config/sxhkd/i3-sxhkdrc"
			menuItem 'Edit Border Width' "$0 --border"
			menuItem 'Reload i3' "$HOME/.config/i3/i3-reload"
			menuItem 'Restart i3' "i3-msg restart"
			menuItem 'Restart sxhkd' "pkill -USR1 -x sxhkd"
		menuEnd
	elif [[ "$wm" == "Openbox" ]]; then
		menuStart
			menuSeparator 'Openbox'
			menuItem 'Settings' "obconf"
			menuItem 'Edit Autostart' "exo-open $HOME/.config/openbox/autostart"
			menuItem 'Edit Keybinds' "exo-open $HOME/.config/openbox/rc.xml"
			menuItem 'Restart' "openbox --restart"
			menuItem 'Reconfigure' "openbox --reconfigure"
		menuEnd
	fi
fi
