#!/bin/bash

## Weather data
# you need to get a free API key from https://home.openweathermap.org for the script to be functional 
KEY=""  # put your Opeanweather API key here

# you also need to sign up on https://www.weatherbit.io/account/create  
# in order to use all the features of this script you need to sign up for an API key
WBKEY=""  # put your WeatherBit API key here 

UNIT="metric"	# Available options : 'metric' or 'imperial'
COUNTRY="country" # put your country name here 
CITY="city" # put your city name here
