#!/bin/bash

## Weather data
# you need to get a free API key from https://home.openweathermap.org for the script to be functional 
KEY="7e6ed49a1a7b802ad1299faa3a5f008d"  # put your Opeanweather API key here

# you also need to sign up on https://www.weatherbit.io/account/create  
# in order to use all the features of this script you need to sign up for an API key
WBKEY="754802f8df8d48f999ae6a283c2a3801"  # put your WeatherBit API key here 

UNIT="metric"	# Available options : 'metric' or 'imperial'
COUNTRY="Syria" # put your country name here 
CITY="Idlib" # put your city name here
