#!/usr/bin/env bash

[[ -f "$HOME/.cache/wal/colors.sh" ]] && source "$HOME/.cache/wal/colors.sh"
[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile"
[[ -z "$bar_style" ]] && bar_style="base" top_padding="23"

hidden=/tmp/syshide.lock

tray(){
	gravity="NE"
	res="$(xrandr --current | awk '/Screen/ {printf("%.0f\n", $8)}')"
	if [[ "$res" > 1920 ]]; then 
		width="$(echo $res | awk '{printf("%.0f\n", $1 / 2 * 0.049 + 1920)}')"
	else
		width="$(echo $res | awk '{printf("%.0f\n", $1 * 0.049)}')"
	fi
	color="$(pastel mix -f 0.4 $color8 $color0 | pastel format hex)"
	
	if [[ "$bar_style" == "base" ]]; then 
		geometry="1x1-5+28"
	elif [[ "$bar_style" == "minimal" ]]; then 
		geometry="1x1-$width-34"
	elif [[ "$bar_style" == "bionic" ]]; then 
		geometry="1x1-$width+45"
	fi
	
	config="--background $color --geometry $geometry --grow-gravity $gravity --icon-gravity $gravity --vertical false --slot-size 32 --kludges force_icons_size"
	
	if [[ "$(pidof stalonetray)" ]]; then
		if [[ ! -e "$hidden" ]]; then
			polybar-msg action "#systray.hook.1"
			xdo hide -n stalonetray
			touch "$hidden"
			killall -9 systray
		else
			polybar-msg action "#systray.hook.0"
			xdo show -n stalonetray
			xdo raise -n stalonetray
			rm "$hidden"
			sleep 5 && tray
		fi
	else
		stalonetray $(echo $config) &
		tray
	fi
}

i3_tray(){
	polytray="$(pgrep -a polybar | grep systray | cut -d ' ' -f1)"
	if [[ "$polytray" ]]; then
		if [[ ! -e "$hidden" ]]; then
			polybar-msg action "#systray.hook.1"
			xdo hide -p "$polytray"
			touch "$hidden"
			pkill -9 systray
		else
			polybar-msg action "#systray.hook.0"
			xdo show -p "$polytray" 
			rm "$hidden"
			sleep 5 && i3_tray
		fi
	else
		polybar systray -q -c "$HOME/.config/polybar/$bar_style/config.ini" & disown
		i3_tray
	fi
}

if [[ "$XDG_CURRENT_DESKTOP" == "i3" ]]; then 
	i3_tray
else
	tray
fi
