#!/bin/bash

hidden=/tmp/syshide.lock
res="`xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1`"


if [[ $(pidof stalonetray) ]]; then
	if [[ ! -e $hidden ]]; then
		polybar-msg action "#systray.hook.1"
		xdo hide -n stalonetray
		touch "$hidden"
	else
		polybar-msg action "#systray.hook.0"
		xdo show -n stalonetray
		xdo raise -n stalonetray
		rm "$hidden"
	fi
else
	if [[ $res -gt "1920" ]]; then
		new="$(( $res - 1920 + 4 ))"
		stalonetray --geometry 1x1-$new+27
	else
		stalonetray &
	fi
fi
