#!/bin/bash

## Get the API keys and city from a different file
source "$HOME"/.config/polybar/scripts/info

## Collect data
cache_dir="$HOME/.cache/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_icon=${cache_dir}/weather-icon
cache_weather_rofi=${cache_dir}/weather-rofi

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p ${cache_dir}
fi

## Get City
if [[ -z $CITY ]]; then 
	CITY=$(wget --timeout=2 http://ipinfo.io/city -qO -)
fi

## Get data
get_weather_data() {
		weather=$(wget -qO- "https://api.openweathermap.org/data/2.5/weather?q=$CITY,$COUNTRY&appid=$KEY&units=$UNIT")
		echo "${weather}"

	if [ ! -z "$weather" ]; then
		weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
		weather_icon_code=$(echo "$weather" | jq -r ".weather[].icon" | head -1)
		weather_description=$(echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g")
		if [[ "$(( $(date +%M) % 30))" == 0 ]]; then
		  altweather=$(wget -qO- --header='Accept: application/json' "https://api.weatherbit.io/v2.0/current?city=$CITY&country=$COUNTRY&key=$WBKEY")
			city=$(echo "$weather" | jq -r ".name") 
			humidity=$(echo "$weather" | jq -r ".main.humidity") 
			windspeed=$(echo "$weather" | jq -r ".wind.speed") 
			uv=$(echo "$altweather" | jq -r ".data[].uv" | cut -c 1-4)
			aqi=$(echo "$altweather" | jq -r ".data[].aqi")
			dewpt=$(echo "$altweather" | jq -r ".data[].dewpt")
			precipitation=$(echo "$altweather" | jq -r ".data[].precip")
			
			cat > "$cache_weather_rofi" <<- EOF
			City: $city 
			Dew Point: $dewpt°C 
			Humidity: $humidity% 
			UV Index: $uv 
			Air Quality: $aqi
			Precipitation: $(printf "%.2f" $precipitation)%
			Windspeed: $windspeed m/s \n
			EOF
		fi
		
		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "50n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "01d"  ]; then
			weather_icon="盛 "
		elif [ "$weather_icon_code" == "01n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "02d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "02n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "03d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "03n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "04d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "04n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "09d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "09n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "10d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "10n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "11d"  ]; then
			weather_icon="ﭼ " 
		elif [ "$weather_icon_code" == "11n"  ]; then
			weather_icon="ﭼ " 
		elif [ "$weather_icon_code" == "13d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "13n"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "40d"  ]; then
			weather_icon=" "
		elif [ "$weather_icon_code" == "40n"  ]; then
			weather_icon=" "
		else 
			weather_icon=" "
		fi
		echo "$weather_icon" >  ${cache_weather_icon}
		echo "$weather_description" > ${cache_weather_stat}
		echo "$weather_temp""° " > ${cache_weather_degree}

	else
		wttr=$(curl wttr.in/$CITY?format="%t+%C\n")
		if [[ -n $wttr ]]; then
			echo $wttr > ${cache_weather_stat}
		else 
			echo "Weather Unavailable" > ${cache_weather_stat}
		fi
		echo " " > ${cache_weather_icon}
		echo " " > ${cache_weather_degree}
	fi
}

## Execute
if [[ "$1" == "--getdata" ]]; then
	get_weather_data
elif [[ "$1" == "--icon" ]]; then
	cat ${cache_weather_icon}
elif [[ "$1" == "--temp" ]]; then
	cat ${cache_weather_degree}
elif [[ "$1" == "--stat" ]]; then
	cat ${cache_weather_stat}
elif [[ "$1" == "--full" ]]; then
	get_weather_data &> /dev/null
	cat ${cache_weather_icon} ${cache_weather_degree} ${cache_weather_stat} | tr -d '\n'
fi
