swipe:
  3:
    left:
      sendkey: 'LEFTALT+RIGHT'
      
    right:
      sendkey: 'LEFTALT+LEFT'

    up:
      command: 'workspace prev'
      threshold: 0.1
      interval: 1.8

    down:
      command: 'workspace next'
      threshold: 0.1
      interval: 1.8
        
  4:
    left:
      command: 'playerctl next'
    right:
      command: 'playerctl previous'
    up: 
      command: 'volume --inc'
      threshold: 0.01
      interval: 0.15
    down: 
      command: 'volume --dec'
      threshold: 0.01
      interval: 0.15


interval:
  swipe: 1.0
  
threshold:
  swipe: 1.0
  
hold:
  4:
    command: "playerctl play-pause" # Activity
    threshold: 0.15

plugin: 
  executors:
    wmctrl_executor:
      wrap-navigation: true
