#!/usr/bin/env bash

## Commands Executed By Openbox Powermenu

## Options #############################################
if  [[ $1 = "--logout" ]]; then
	current_desktop=$(wmctrl -m |sed -n 1p | sed -e 's/Name: //g') 
	if [[ $current_desktop == "Openbox" ]]; then
		openbox --exit
	elif [[ $current_desktop == "i3" ]]; then
		i3 exit
	elif [[ $current_desktop == "bspwm" ]]; then
		bspc quit
	fi
elif  [[ $1 = "--lock" ]]; then
	lockscreen
elif  [[ $1 = "--suspend" ]]; then
	systemctl suspend
elif  [[ $1 = "--reboot" ]]; then
	systemctl reboot
elif  [[ $1 = "--shutdown" ]]; then
	systemctl poweroff
fi
