#!/usr/bin/bash

# Policy Authentication Agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi 

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &

# variables
scripts=~/.scripts

# gsettings
gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor'
gsettings set org.gnome.desktop.interface font-name 'Noto Sans 9'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
gsettings set org.gnome.desktop.interface cursor-theme 'Fluent-dark'


# notification daemon
#swaync &

# waybar
#$scripts/launch_waybar &
# $scripts/dynamic &

# wallpaper

# effects
# $scripts/tools/rgb &

# Applets
#blueman-applet &

# music daemon
#mpd &

# other
#hyprctl setcursor Sweet-cursors 24
#wl-paste --watch cliphist store &
#notify-send -a aurora "hello $(whoami)" &

