#!/usr/bin/env bash

# Autostart Programs ----------------------------------------#

[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile" || conky="On"

# XDG Autostart 
[[ ! $(pgrep -f polkit-gnome-authentication-agent) ]] && xdg-autostart

# Keybinds
killall -q -9 sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/bspwm-sxhkdrc &

# Enable Super Keys For Menu
killall -q -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Polkit agent
[[ ! $(pgrep -f polkit-gnome-authentication-agent) ]] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# xfce4-settings daemon
xfsettingsd &

# Compositor 
compositor --start &

# Dunst
dunst &

# Restore Wallpaper
wal -Re &
"$HOME"/.local/bin/wpgtk run &

# Launch Polybar
"$HOME"/.config/polybar/launch.sh &

# CopyQ
copyq --start-server &

# Plank
killall -q -9 plank
plank &

# Conky
[[ "$conky" == "On" ]] && "$HOME"/.local/bin/conky.sh &

# Fix Plank
bspc subscribe node_add | while read -r _
do
	xdo raise -N Plank
done &
