#!/usr/bin/env bash

## Autostart Programs ----------------------------------------#

source ~/.profile

## XDG Autostart 
xdg-autostart &

## Keybinds
killall -9 sxhkd
exec sxhkd &

# Enable Super Keys For Menu
killall -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
	#/usr/lib/xfce-polkit/xfce-polkit &
#fi 

## Fix cursor
xsetroot -cursor_name left_ptr &

## xfce4-settings daemon
xfsettingsd &

## Dunst
dunst &

## Restore Wallpaper
wal -Re &
sh ~/.scripts/wpgtk run &

## Launch Polybar
sh ~/.config/polybar/launch.sh &

## Picom 
picom -b &

## CopyQ
copyq --start-server &

## Thunar 
killall -9 thunar
thunar --daemon  &

## Plank
plank &

## Conky
if [ $conky == "On" ]; then 
	sh ~/.local/bin/conky.sh &
fi

## Fix Plank
bspc subscribe node_add | while read -r _
do
  xdo raise -N Plank
done &
