#!/usr/bin/env bash

# Autostart Programs ----------------------------------------#

[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile" || conky="On"

# XDG Autostart 
[[ ! $(pgrep xfce-polkit) ]] && xdg-autostart &

# Keybinds
killall -9 sxhkd
sxhkd &

# Enable Super Keys For Menu
killall -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Polkit agent
#if [[ ! $(pidof xfce-polkit) ]]; then /usr/lib/xfce-polkit/xfce-polkit & ;fi 

# xfce4-settings daemon
xfsettingsd &

# Picom 
picom -b &

# Dunst
dunst &

# Restore Wallpaper
wal -Re &
"$HOME"/.local/bin/wpgtk run &

# Launch Polybar
"$HOME"/.config/polybar/launch.sh &

# CopyQ
copyq --start-server &

# Thunar 
#thunar --daemon &

# Plank
killall -9 plank
plank &

# Conky
[[ "$conky" == "On" ]] &&
	"$HOME"/.local/bin/conky.sh &

# Fix Plank
bspc subscribe node_add | while read -r _
do
	xdo raise -N Plank
done &
