#!/usr/bin/env bash

### Get colors from Wal --------------------------------------#
if [[ -f "$HOME/.theme" ]]; then source "$HOME/.theme" ; else window_border="3" ;fi

source "$HOME/.cache/wal/colors.sh"
bspc config focused_border_color "$color5" 
bspc config normal_border_color "$color10"
bspc config active_border_color "$color12"
bspc config presel_feedback_color "$color9"

bspc config border_width "$window_border"
