#!/usr/bin/env bash

### Get colors from .Xresources ------------------------------#
#xrdb ~/.Xresources
#getcolors() {
	#FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	#BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	#BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	#RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	#GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	#YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	#BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	#MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	#CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	#WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
#}
#getcolors

### Get colors from Wal --------------------------------------#

source "$HOME/.cache/wal/colors.sh"
bspc config focused_border_color "$color9" 
bspc config normal_border_color "$color10"
bspc config active_border_color "$color12"
bspc config presel_feedback_color "$color9"


bspc config border_width 3
