#!/usr/bin/env bash

## Environtment
export PATH="${PATH}:$HOME/.local/bin"

## Configuration --------------------------------------------#

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七' '八'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '九' '十'
		let name++
	done
}
workspaces

bspc config window_gap 10
bspc config split_ratio 0.50
sh ~/.config/bspwm/bsp-border
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## special rules
declare -a floating=(alacritty-float Lxappearance obs
	Onboard Yad '*:*:Picture-in-Picture' Viewnior
	feh Nm-connection-editor stalonetray Pavucontrol
	copyq '*:*:Library' Trackma-gtk Blueman-manager
	Xfce4-appearance-settings Xfce4-mouse-settings
	Xfce4-settings-manager Sxiv Trackma-gtk gnome-calculator
	org.gnome.Weather Xfce4-display-settings Steam Wpg
	TelegramDesktop KotatogramDesktop)

for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

# Force tile windows
declare -a tiled=(Zathura)
for i in "${tiled[@]}"; do
	bspc rule -a "$i" manage=on state=tiled
done

bspc rule -a Plank manage=off locked=on border=off state=floating focus=off

## Autostart Programs ----------------------------------------#

## XDG Autostart 
xdg-autostart &

## Keybinds
killall -9 sxhkd
exec sxhkd &

# Enable Super Keys For Menu
killall -9 xcape
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
	#/usr/lib/xfce-polkit/xfce-polkit &
#fi 

## Fix cursor
xsetroot -cursor_name left_ptr &

## xfce4-settings daemon
xfsettingsd &

## Dunst
dunst &

## Restore Wallpaper
wal -Re &
sh ~/.scripts/wpgtk run &

## Launch Polybar
sh ~/.config/polybar/launch.sh &
bspc config -m focused top_padding 23 
bspc config -m focused bottom_padding 23 

## Picom 
picom -b &

## CopyQ
copyq --start-server &

## Plank
plank &

## Conky
sh ~/.local/bin/conky.sh &

## Fix Plank
bspc subscribe node_add | while read -r _
do
  xdo raise -N Plank
done &
