#!/usr/bin/bash

if [[ -f ~/.zprofile ]]; then source ~/.zprofile ;else bar_style="base" ;fi

killall -q waybar

# env GTK_DEBUG=interactive
if [ "$bar_style" == "base" ]; then 
	waybar -l info -c ~/.config/waybar/config -s ~/.config/waybar/style.css > /tmp/waybar.log 2>&1 & disown
elif [ "$bar_style" == "minimal" ]; then 
	waybar -l info -c ~/.config/waybar//minimal/config-minimal -s ~/.config/waybar/style.css > /tmp/waybar.log 2>&1 & disown
fi
