#!/bin/bash

if [[ $1 == "picker" ]]; then
    cd $HOME
    eww close-all
    color-gpick
elif [[ $1 == "settings" ]]; then
    cd $HOME
    eww close-all
    xfce4-settings-manager
elif [[ $1 == "volume" ]]; then
    cd $HOME
    eww close-all
    pavucontrol
elif [[ $1 == "display" ]]; then
    cd $HOME
    eww close-all
    xfce4-display-settings
elif [[ $1 == "power" ]]; then
    cd $HOME
    eww close-all    
    ~/.config/rofi/bin/powermenu
elif [[ $1 == "exit" ]]; then
    cd $HOME
    eww close-all
elif [[ $1 == "blue" ]]; then
    cd $HOME
    eww close-all
    blueman-manager
elif [[ $1 == "wifi" ]]; then
    cd $HOME
    eww close-all
    ~/.config/rofi/bin/network_menu 
fi 
