#!/bin/bash

[ ! -d $cache_dir ] && mkdir $cache_dir

cache_dir="$HOME/.cache/eww"
cache="$cache_dir/info-center.eww"
config="$HOME/.config/eww"

run () {
	eww -c $config open notification-panel
	sleep 0.6
	eww -c $config update notification-panel=true
}

if [[ ! `pidof eww` ]]; then
	eww -c $config daemon
	sleep 1
else
	if [ ! -f $cache ]; then
		touch $cache
		run
	else
		eww -c $config update notification-panel=false
		sleep 0.6
		eww -c $config close notification-panel
		rm $cache
	fi
fi
